### ISSUE TITLE
Fade images in hero unit

### ISSUE THREAD

**Issue by dtinth** [reactbkk/2.0.0#1]
![image](https://cloud.githubusercontent.com/assets/193136/26118740/2ad759fa-3a95-11e7-80e2-75e307dcc5b9.png)

รูปแรกอยู่ใน Repo แล้ว

รูปสอง

![picture2](https://cloud.githubusercontent.com/assets/193136/26200621/2d440318-3bf9-11e7-909e-44cab5c9c4a8.jpg)

รูปที่สาม

![picture3](https://cloud.githubusercontent.com/assets/193136/26200625/3074fc04-3bf9-11e7-8764-b5c0adeb5bd2.jpg)

**Comment by zapkub** [comment]
จองแล้ว ห้ามแย่ง ใครแย่งขอให้ ขี้แตกจู๊ดๆ

ล้อเล่นนะ เวรกรรม ไม่มีใครทำอันนี้เลย

**Comment by jirawatfreedom** [comment]
ง้อววววว

**Comment by dtinth** [comment]
Closed by #83.
