### ISSUE TITLE
Add menu mobile 

### ISSUE THREAD

**Issue by Thanakorn-ki** [reactbkk/2.0.0#107]

**Comment by dtinth** [comment]
@salapao2136 

Did you mean to add a hamburger menu?

In this case, I suggest keeping the original MainNavigation intact and display the mobile hamburger menu only when user scrolled past the HeroUnit.

This allows mobile users, during the event, to open and app and jump to schedule in one tap.

![image](https://cloud.githubusercontent.com/assets/193136/26282169/cb3191a6-3e35-11e7-9da4-af76b663670d.png)

**Comment by Thanakorn-ki** [comment]
Good idea @dtinth
