### ISSUE TITLE
Clicking at down arrow in HeroUnit scrolls user to ticket section

### ISSUE THREAD

**Issue by hibikiledo** [reactbkk/2.0.0#109]
__If you would like to work on this issue, please leave a comment__

## Issue
Clicking at down arrow in HeroUnit scrolls user to ticket section. This behaviour is incorrect.
**It should scroll user to About section**

### Down Arrow
<img width="887" alt="down-arrow" src="https://cloud.githubusercontent.com/assets/4034609/26282099/469b54c8-3e34-11e7-926b-a0d26d68de90.png">

### About section
<img width="850" alt="about" src="https://cloud.githubusercontent.com/assets/4034609/26282113/a11908b4-3e34-11e7-8e1e-3fd087d13f07.png">

**Comment by patcharida-aom** [comment]
I want to fix this issue @hibikiledo :]
