### ISSUE TITLE
Change countdown to count towards 2nd tickets round instead of event start

### ISSUE THREAD

**Issue by dtinth** [reactbkk/2.0.0#111]
### Please leave a comment in this issue if you are going to work on it!

Next batch of tickets will be available on May 25th, 18:00 (UTC+7).

Let’s change the countdown to that date.

Before ticket release (we add a text to make it clear what the countdown is counting towards):

![image](https://cloud.githubusercontent.com/assets/193136/26282507/edcf377a-3e3c-11e7-842d-c89c45f6bf4d.png)

When ticket is released, the countdown is replaced by a text saying that the remaining tickets are now available:

![rtrl](https://cloud.githubusercontent.com/assets/193136/26294752/3d4ace1e-3ef0-11e7-8d21-203885d4f6fd.png)

The color code for the button is `#FF5274`, found in the design sketch file.

We must make sure that changing between these two states does not cause the layout to jump veritcally.

**Comment by buffaly** [comment]
I think use opacity 0.3 to info disable button

**Comment by dtinth** [comment]
From the conversation, using a red button can be confusing, so when countdown reaches zero, we make it display a text instead…

**Comment by rennerwins** [comment]
I'm working on it.
