### ISSUE TITLE
Schedule updates

### ISSUE THREAD

**Issue by dtinth** [reactbkk/2.0.0#120]
### Please leave a comment in this issue if you are going to work on it!

There are still few missing schedule items :)

- 16:45~17:00 — (Break)
- 17:00~17:20 — Fireside Chat
- 17:20 onwards — Networking Dinner

**Comment by kolopo16** [comment]
Could I add these items krub?

**Comment by dtinth** [comment]
@kolopo16 Please go ahead! :)

Please note that the comment is for telling everyone that you are working on it and is not a reservation. But if it doesn't take a long time, we will wait to review your PR first.
