### ISSUE TITLE
Mobile navigation: Should highlight current section

### ISSUE THREAD

**Issue by dtinth** [reactbkk/2.0.0#131]
### Please leave a comment if you are going to work on this issue, thank you.

Right now, in the mobile navigation there is no indication about which section I am viewing. Maybe better to add an indicator (such as making the text bold) for current item.

![image](https://cloud.githubusercontent.com/assets/193136/26338865/d7b5ece6-3fad-11e7-8b94-20e96a79e920.png)

**Comment by nontachaiwebdev** [comment]
In progess kub
