### ISSUE TITLE
Sponsor heading should be centered

### ISSUE THREAD

**Issue by WiNloSt** [reactbkk/2.0.0#148]
I think somehow the sponsor heading just gone haywire.

It should be centered along with other headings.
![image](https://cloud.githubusercontent.com/assets/1937582/26432656/7b253f10-4127-11e7-84c4-2f4e856bd5c5.png)

**Comment by abzeede** [comment]
I've already sent PR https://github.com/reactbkk/2.0.0/pull/149.
