### ISSUE TITLE
ออกแบบรูป Facebook shareable image (og:image)

### ISSUE THREAD

**Issue by dtinth** [reactbkk/2.0.0#15]
Need image of size 1200x630 for sharing on Facebook ^_^

**Comment by dtinth** [comment]
ใส่รูปแก้ขัดไปก่อนนะครับบ :3

<img src="https://cloud.githubusercontent.com/assets/193136/26197053/232bb2a8-3beb-11e7-9058-3e34af946bc9.jpg" width="600" height="315" />

**Comment by ArnonHongklay** [comment]
ใส่ไปแล้ว https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Freactbkk.github.io%2F2.0.0%2F

**Comment by dtinth** [comment]
@nonmadden ใช่ครับ ตอนนี้เอารูปด้านบนใส่เป็น og:image ไปก่อนแล้ว แต่รู้สึกว่ารูปนี้มันแทบไม่มีข้อมูลอะไรเลย เลยคิดว่ารูปนี้น่าจะออกแบบให้ดีขึ้นได้ครับบ

**Comment by lukkiddd** [comment]
![artboard](https://cloud.githubusercontent.com/assets/4519517/26217770/cb66b598-3c32-11e7-842e-c34d0cc32668.png)

**Comment by buffaly** [comment]
![image](https://cloud.githubusercontent.com/assets/4066162/26278645/f4f3cfb6-3dc9-11e7-92c9-6459eda80ccd.png)

**Comment by dtinth** [comment]
@buffaly Actually, I like the idea by @lukkiddd of using code to annotate the date and venue; it looks very geeky. What do you think about incorporating that idea into our shareable image?

**Comment by buffaly** [comment]
sound good~ I will try to imprement that idea
