### ISSUE TITLE
Ticket sold out and bring count down back

### ISSUE THREAD

**Issue by n3tr** [reactbkk/2.0.0#154]
Should we change wording 'Ticket sold out' and bring count down back?

**Comment by dtinth** [comment]
👍

**Comment by wuttitorn** [comment]
I can fixed this issue but I don't know how to commit the source code.

**Comment by PanJ** [comment]
You have to fork this repo and commit your changes to your forked repo.
Then create a pull request to merge your repo with this repo.

**Comment by wuttitorn** [comment]
@PanJ : I'm not sure that I create a pull request to merge completed or not ? Could you help me to check it pls. I'm a very newbie for GitHub T-T

**Comment by PanJ** [comment]
@wuttitorn What you are doing is right. You just have to edit description to specify issue you are solving. (see [comment](https://github.com/reactbkk/2.0.0/pull/155#issuecomment-304941888))
