### ISSUE TITLE
Design schedule section

### ISSUE THREAD

**Issue by dtinth** [reactbkk/2.0.0#20]
- Design for mobile first
- Maybe have a link to fullscreen mode that can be added to home screen (PWA)

**Comment by buffaly** [comment]
Destop
![image](https://cloud.githubusercontent.com/assets/4066162/26278439/d0051f2a-3dc4-11e7-89e3-33b4470dc99d.png)

**Comment by buffaly** [comment]
Mobile
![image](https://cloud.githubusercontent.com/assets/4066162/26278466/77857e8e-3dc5-11e7-91ff-8578a824323f.png)

**Comment by dtinth** [comment]
@buffaly My thoughts about the design:

- The lunch break doesn’t have a time range.
- In my opinion, the ending time is not necessary. Just starting time should be enough?
- The avatars are not aligned horizontally. Is this intentional?
- The topic’s font is not consistent with the rest of the page. Is this intentional?
- Should we add some indicator if a session is beginner or intermediate?

**Comment by buffaly** [comment]
-the time of lunch is not necessary. It is a break point, not need to info people
-need ending time to tell how long is section
-The avatars is on top-left of title
-sorry forget to change font family
-added
![image](https://cloud.githubusercontent.com/assets/4066162/26278930/b33cdd7c-3dd0-11e7-82f4-43564dd4d6f9.png)

**Comment by dtinth** [comment]
Ok, I think we are now ready to tackle #22.
