### ISSUE TITLE
ทำหน้า Schedule

### ISSUE THREAD

**Issue by dtinth** [reactbkk/2.0.0#22]
- The schedule section should be responsive, as we expect people to view it during the event on their mobile phones.
- For design, please see Issue #20.

__If you would like to work on this issue, please leave a comment.__

**Comment by kenshero** [comment]
in progress.

**Comment by dtinth** [comment]
Let’s wait for #20 to get resolved before working on this one.

**Comment by dtinth** [comment]
#20 already has some design, I think this issue is ready to be worked on.
