### ISSUE TITLE
Add description section

### ISSUE THREAD

**Issue by dtinth** [reactbkk/2.0.0#4]
*Please see the discussion below.*

---

Note: If you want to work on this issue, please comment to indicate that you are working on it to prevent confusion/duplicated work.

**Comment by hlex** [comment]
How about thuis issue krub? Could I get more details ?

**Comment by dtinth** [comment]
Thanks for your interest.

The about section is the first section after the HeroUnit. This is the design:

![image](https://cloud.githubusercontent.com/assets/193136/26276855/7bba8f3c-3daa-11e7-9727-5dffc4105cc2.png)

However, we don’t have any text in this section.

So, let’s come up with some text first.

Here is the description from event pop:

> จากเสียงตอบรับที่ดีใน 2 ครั้งที่ผ่านมา กับ React Bangkok 1.0.0 และ 1.1.0 เราได้กลับมาอีกครั้งกับ React Bangkok 2.0.0 ที่ยิ่งใหญ่กว่าเดิม และอัดแน่นไปด้วยความรู้และประสบการณ์จาก Speakers มากมาย
>
> หัวข้อที่จะมีในวันงานแบ่งเป็น 2 track คือ Beginner Track สำหรับผู้ที่มีพื้นฐาน React น้อย และ Intermediate Track สำหรับผู้ที่เขียน React มาบ้างพอสมควรแล้ว

This meetup is different from previous meetups because:

- This is a whole-day event. So it’s more like a conference. 😁
- We have lightning talks, which are short talks submitted from the participants.
- We have networking party afterwards

Also, I think this section should contain the date and place of the event.

**Comment by hibikiledo** [comment]
@salapao2136 has opened (PR #100 ) for this issue.

**Comment by Thanakorn-ki** [comment]
Close #100
