### ISSUE TITLE
เปลี่ยนไอคอนสำหรับ Android

### ISSUE THREAD

**Issue by n3tr** [reactbkk/2.0.0#55]
ตอนนี้เวลาแอดเว็บไปที่ Homescreen หน้าตาไอคอนเป็นแบบนี้

![image](https://cloud.githubusercontent.com/assets/193136/26214141/7c090d82-3c25-11e7-8714-bf117f8e4445.png)

ปัญหาคือ

- ไอคอนผิดอัตราส่วน Aspect ratio (เหมือนถูกบีบให้ผอมๆ)
- ไอคอนไม่ได้ใช้ขนาดตาม Material design
- ข้อความใต้ไอคอนยาวไป (ReactBKK 2.0.0) ใน HomeScreen จึงถูกตัด ควรแก้เป็น ReactBKK ก็พอ

Android คิดว่าน่าจะแก้ใส่ที่ Manifest ได้เลย ทำ Icon มาให้แค่ 2 Size

- 192x192 มีพื้นที่ว่างจากขอบ สำหรับ Android

![192](https://cloud.githubusercontent.com/assets/155392/26212498/f8f1c4d4-3c1f-11e7-99aa-aef86152934a.png)

**Comment by thanabhat** [comment]
pull request #63 ครับ
