### ISSUE TITLE
เปลี่ยนไอคอนสำหรับ iOS

### ISSUE THREAD

**Issue by dtinth** [reactbkk/2.0.0#57]
ตอนนี้ไอคอนใน iOS หน้าตาแบบนี้

![image](https://cloud.githubusercontent.com/assets/193136/26214058/46d91f4e-3c25-11e7-886d-2fdb23ceac27.png)

ปัญหาคือ

- ตอนกด Add to homescreen ชื่อของแอปคือ “React Bangkok 2.0.0” ทำให้ข้อความเห็นได้ไม่หมด ควรเปลี่ยนเป็น ReactBKK ก็พอครับ
- โลโก้เล็กไป

ไฟล์โลโก้ใหม่ขนาด 152x152 ของ iOS

![152](https://cloud.githubusercontent.com/assets/155392/26212497/f8eebf64-3c1f-11e7-8a5d-412e8fea0c29.png)

**Comment by chaintng** [comment]
เพิ่งทำเสร้จทั้ง android และ ios... แตก issue สะงั้น :'( แก้ commit แพร๊บบบ

**Comment by chaintng** [comment]
ส่งงานครับผม :) https://github.com/reactbkk/2.0.0/pull/59

**Comment by dtinth** [comment]
ขอบคุณครับ ตอนแรกผม Assume ว่า Developer จะมีเครื่องไว้เทสต์แค่ชนิดเดียวน่ะครับ 5555

และก็แยก Issue ไว้ เพื่อให้คนมาช่วยกันทำได้หลายๆ คน ครับบ

เดี๋ยวผมมาดูต่อพรุ่งนี้ครับบ วันนี้หมดแรงละ
