### ISSUE TITLE
แบ่ง Speakers เป็น 3 คอลัมน์บนหน้าจอขนาดใหญ่ (Responsive)

### ISSUE THREAD

**Issue by dtinth** [reactbkk/2.0.0#60]
หากหน้าจอมีพื้นที่ แบ่งคอลัมน์ตามรูปแบบนี้ครับ

![image](https://cloud.githubusercontent.com/assets/193136/26214704/8cf31ef6-3c27-11e7-9459-a8903ced9d68.png)

Layout settings ใน Sketch ตามนี้ครับ

![image](https://cloud.githubusercontent.com/assets/193136/26214777/d3942e18-3c27-11e7-8078-857a93d01110.png)

**Comment by lukkiddd** [comment]
#66 คร้าบผม

**Comment by dtinth** [comment]
Closed by #71
