### ISSUE TITLE
Add photos section

### ISSUE THREAD

**Issue by dtinth** [reactbkk/2.0.0#7]
If you would like to work on this issue, please leave a comment on this issue.
Also, in the PR, please write `Closes #7` in the pull request’s __description.__

**Comment by hlex** [comment]
Could you please give more details about this issue krub.

**Comment by dtinth** [comment]
@hlex 

This is the design that we try to build

![Design](https://cloud.githubusercontent.com/assets/193136/26188109/898c7542-3bc7-11e7-8381-8d2e0fe75b93.jpg)

This section will sit between the sponsors section and the speakers section.

However, we don’t have enough photos now, so this issue is on hold.

**Comment by hlex** [comment]
Could I do this section and using temp photos krub ? I want a ticket to an event.

**Comment by hibikiledo** [comment]
@dtinth @buffaly 
Is it possible to start this feature with temp photos ?

What are other requirements ?
Eg. scrollable, click to view large image, etc

**Comment by dtinth** [comment]
@hibikiledo @hlex 

I prefer to not put up temporary photos to the website, as that would make the content unrelated/repetitive.

It is fine to start this feature right now, but it will not get merged unless one of these conditions:

- We have actual photos, or
- The photos section is hidden from the actual website, viewable in development mode

For first version, just a static photo grid is fine.
