### ISSUE TITLE
Smoothing scroll effect for navigation

### ISSUE THREAD

**Issue by lukkiddd** [reactbkk/2.0.0#78]
#77 💃  🍴 

---

Edit (@dtinth):

เนื่องจากโปรเจกต์เราใช้ไลบรารี่ [react-scroll](https://github.com/fisshy/react-scroll) อยู่แล้ว จึงแนะนำให้แก้ Issue นี้ด้วย react-scroll เช่นเดียวกันครับ (ไม่เอา jQuery นะครับบ)

**Comment by tanaphonble** [comment]
#91 รบกวนตรวจสอบด้วยครับ

**Comment by dtinth** [comment]
@tanaphonble Sorry, there are many issues that tries to solve this already (#81 #84 #88 #91), with the most promising one being #81.

Unfortunately, as none of the pull requests mentions this issue (like “Closes #78”), there is no indication that anyone is working on this issue. Sorry, I forgot to update this issue to say that someone is already working on it.

To prevent further duplication of effort, I have removed the star from this issue.

Thank you for your understanding.
