### ISSUE TITLE
iOS: When adding to home screen, the app should launch in full-screen mode

### ISSUE THREAD

**Issue by dtinth** [reactbkk/2.0.0#86]
__Steps to reproduce:__

- Go to https://reactbkk.github.io/2.0.0/
- Add to home screen
- Open the app from the home screen

__Expected result:__

The website should open in full-screen mode

__Actual result:__

The website opened in Safari.

**Comment by kingkong64** [comment]
is campatible now?

**Comment by n3tr** [comment]
resolved by #95
