### ISSUE TITLE
ใส่โลโก้จางๆ เป็น Background

### ISSUE THREAD

**Issue by dtinth** [reactbkk/2.0.0#9]
Please see the conversation below for more details.

__If you would like to work on this issue, please leave a comment.__

**Comment by dekdekbaloo** [comment]
@dtinth Can you please describe more detail on this?

**Comment by dtinth** [comment]
The task here is to add a subtle React Bangkok logo in the background.

The first one is at the right half of the screen:

![image](https://cloud.githubusercontent.com/assets/193136/26282106/82738a6a-3e34-11e7-92f6-5913db8bb3f3.png)

The second one on the left half:

![image](https://cloud.githubusercontent.com/assets/193136/26282110/901f4eb0-3e34-11e7-9a2c-8d85459a58dc.png)

Ideally, the logo would have parallax scrolling.

**Comment by dekdekbaloo** [comment]
@dtinth Thank you for the explanation.

**Comment by patcharida-aom** [comment]
@dtinth ขอจองนะคะ

**Comment by dtinth** [comment]
@patcharida-aom You can comment on the issue to indicate that you are working on an issue. However, we don’t have any reservation systems here yet.

My recommendation is to break down the task into smaller tasks and ship in working increments. For example, for the first version, having a background without parallax effect is acceptable. Then we can add another issue to add parallax effect, which might be solved by another person.

**Comment by dtinth** [comment]
To clarify about the lack of a reservation system:

This campaign runs for only one week. Introducing a task reservation system poses a risk of a task being reserved but not being worked on and delivered in a timely manner. Otherwise, we need to put strict time limits in how long a task can be reserved as well.

__We now ask everyone who works on an issue to comment on the issue indicating that they are going to work on it.__ So from now, if you said that you will work in some issue, but someone else sent a pull request before you are able to submit one (without indicating that they will work on it beforehand), we will try to wait for you to finish your work first. However, we can’t wait if it takes too long.

Anyway, we try to make it so that there are no wasted effort. Although not all PRs will get merged, we will try to review all of them, so that at least everyone will learn from their work. I hope this is fair enough.

**Comment by patcharida-aom** [comment]
@dtinth เข้าใจแล้วค่ะ :)
