### ISSUE TITLE
Improve Google PageSpeed Insight Score

### ISSUE THREAD

**Issue by n3tr** [reactbkk/2.0.0#93]
ตอนนี้ PageSpeed Score เราตกลงมาเหลือแค่ 37-18/100 😢 

![screen shot 2560-05-20 at 5 31 20 pm](https://cloud.githubusercontent.com/assets/155392/26275059/51af0de4-3d82-11e7-803b-522be4ff9712.png)

**Comment by dtinth** [comment]
PageSpeed for mobile is now at 81/100, which is the maximum we can do on GitHub pages now!

![image](https://cloud.githubusercontent.com/assets/193136/26277464/302bb49e-3db2-11e7-8e0c-356ffeca3a85.png)

On Desktop, one more image could be optimized.

![image](https://cloud.githubusercontent.com/assets/193136/26277471/4901aec4-3db2-11e7-95d7-fec4440d0091.png)

**Comment by n3tr** [comment]
fixed in #98 

I will close this issue for now since we got a good result so far.
